# Generated by Django 5.2 on 2025-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('razao', models.CharField(max_length=255)),
                ('fantasia', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('bandeira', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('unidade_de_medida', models.CharField(max_length=10)),
                ('preco_revenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_coleta', models.DateField()),
            ],
            options={
                'db_table': 'postos_combustiveis',
            },
        ),
    ]
